language: perl
perl:
#  - "5.16"
#  - "5.18"
#  - "5.18-shrplib"
#  - "5.20"
#  - "5.20-shrplib"
#  - "5.22"
#  - "5.22-shrplib"
#  - "5.24"
#  - "5.24-shrplib"
#  - "5.26"
  - "5.26-shrplib"
os:
  - linux
env:
  - CC=gcc && CXX=g++
  - CC=clang && CXX=clang++

addons:
  apt:
    update: true
    packages:
      - nasm
      - rsync
      - zlib1g-dev
      - libmodule-install-perl
# We can use this again once 10.10 is deprecated.
#  homebrew:
#    update: true
#    packages:
#      - nasm
#      - rsync


matrix:
  include:
    - name: "osx:10.10_xcode:6.4"
      language: cpp
      os: osx
      osx_image: xcode6.4
      # Need to explicitly set env here, to avoid the build matrix growing
      # across the multiple Linux env's (gcc and clang both map to clang on OSX)
      env: EVERYTHING=awesome
    - name: "osx:10.13_xcode:10.1"
      language: cpp
      os: osx
      osx_image: xcode10.1
      env: EVERYTHING=awesome
    - name: "osx:10.13_xcode:10"
      language: cpp
      os: osx
      osx_image: xcode10
      env: EVERYTHING=awesome
    - name: "osx:10.13_xcode:9.4"
      language: cpp
      os: osx
      osx_image: xcode9.4
      env: EVERYTHING=awesome
    - name: "osx:10.13_xcode:9.3"
      language: cpp
      os: osx
      osx_image: xcode9.3
      env: EVERYTHING=awesome
    - name: "osx:10.12_xcode:9.2"
      language: cpp
      os: osx
      osx_image: xcode9.2
      env: EVERYTHING=awesome
    - name: "osx:10.12_xcode:9.1"
      language: cpp
      os: osx
      osx_image: xcode9.1
      env: EVERYTHING=awesome
    - name: "osx:10.12_xcode:9"
      language: cpp
      os: osx
      osx_image: xcode9
      env: EVERYTHING=awesome
    - name: "osx:10.12_xcode:8.3"
      language: cpp
      os: osx
      osx_image: xcode8.3
      env: EVERYTHING=awesome
    - name: "osx:10.12_xcode:8.0"
      language: cpp
      os: osx
      osx_image: xcode8
      env: EVERYTHING=awesome
    - name: "osx:10.11_xcode:7.3"
      language: cpp
      os: osx
      osx_image: xcode7.3

install: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nasm rsync      ; fi

script:
  - cd CPAN
  - bash -o xtrace -o errexit buildme.sh
