language: perl
perl:
  - "5.18"
os:
  - linux
env:
  - CC=gcc && CXX=g++
  - CC=clang && CXX=clang++

addons:
  apt:
    packages:
      - nasm
      - rsync
      - zlib1g-dev
      - libmodule-install-perl
  homebrew:
    packages:
      - nasm
      - rsync
      - gettext


matrix:
  include:
    - name: "perl_osx"
      language: cpp
      os: osx
      env: 
        - EVERYTHING=awesome
      script:
        - perl -V
        - cd CPAN
        - bash -o errexit buildme.sh Media::Scan

install: true

script:
  - cd CPAN
#  - bash -o errexit buildme.sh

notifications:
  email:
    - m.kempe@gmail.com

