language: perl
perl:
#  - "5.16"
#  - "5.18"
#  - "5.18-shrplib"
#  - "5.20"
#  - "5.20-shrplib"
#  - "5.22"
#  - "5.22-shrplib"
#  - "5.24"
#  - "5.24-shrplib"
#  - "5.26"
  - "5.26-shrplib"
os:
  - linux
env:
  - CC=gcc && CXX=g++
#  - CC=clang && CXX=clang++

addons:
  apt:
    update: true
    packages:
      - nasm
      - rsync
      - zlib1g-dev
      - libmodule-install-perl
# We can use this again once 10.10 is deprecated.
#  homebrew:
#    update: true
#    packages:
#      - nasm
#      - rsync


matrix:
  include:
    - name: "osx:10.10_xcode:6.4"
      language: cpp
      os: osx
      osx_image: xcode6.4
      env:
        - EVERYTHING=awesome
      script:
        - brew update
        - rvm install ruby-2.3.5
        - rvm --default use ruby-2.3.5
        - rvm install ruby-2.3.5
        - rvm ruby-2.3.5 do brew update
        - rvm ruby-2.3.5 do brew install nasm
        - rvm ruby-2.3.5 do brew install rsync
        - cd CPAN
        - bash -o errexit buildme.sh
    - name: "osx:10.13_xcode:10.1"
      language: cpp
      os: osx
      osx_image: xcode10.1
      addons: {homebrew: {update: [true]}} 
      addons: {homebrew: {packages: [[nasm], [rsync]]}} 
      env: 
        - EVERYTHING=awesome
      script:
        - cd CPAN
        - bash -o errexit buildme.sh
    - name: "osx:10.13_xcode:10"
      language: cpp
      os: osx
      osx_image: xcode10
      addons: {homebrew: {update: [true]}}
      addons: {homebrew: {packages: [[nasm], [rsync]]}}
      env:
        - EVERYTHING=awesome
      script:
        - cd CPAN
        - bash -o errexit buildme.sh
    - name: "osx:10.13_xcode:9.4"
      language: cpp
      os: osx
      osx_image: xcode9.4
      addons: {homebrew: {update: [true]}}
      addons: {homebrew: {packages: [[nasm], [rsync]]}}
      env:
        - EVERYTHING=awesome
      script:
        - cd CPAN
        - bash -o errexit buildme.sh
    - name: "osx:10.13_xcode:9.3"
      language: cpp
      os: osx
      osx_image: xcode9.3
      addons: {homebrew: {update: [true]}}
      addons: {homebrew: {packages: [[nasm], [rsync]]}}
      env:
        - EVERYTHING=awesome
      script:
        - cd CPAN
        - bash -o errexit buildme.sh
    - name: "osx:10.12_xcode:9.2"
      language: cpp
      os: osx
      osx_image: xcode9.2
      addons: {homebrew: {update: [true]}}
      addons: {homebrew: {packages: [[nasm], [rsync]]}}
      env:
        - EVERYTHING=awesome
      script:
        - cd CPAN
        - bash -o errexit buildme.sh
    - name: "osx:10.12_xcode:9.1"
      language: cpp
      os: osx
      osx_image: xcode9.1
      addons: {homebrew: {update: [true]}}
      addons: {homebrew: {packages: [[nasm], [rsync]]}}
      env:
        - EVERYTHING=awesome
      script:
        - cd CPAN
        - bash -o errexit buildme.sh
    - name: "osx:10.12_xcode:9"
      language: cpp
      os: osx
      osx_image: xcode9
      addons: {homebrew: {update: [true]}}
      addons: {homebrew: {packages: [[nasm], [rsync]]}}
      env:
        - EVERYTHING=awesome
      script:
        - cd CPAN
        - bash -o errexit buildme.sh
    - name: "osx:10.12_xcode:8.3"
      language: cpp
      os: osx
      osx_image: xcode8.3
      addons: {homebrew: {update: [true]}}
      addons: {homebrew: {packages: [[nasm], [rsync]]}}
      env:
        - EVERYTHING=awesome
      script:
        - cd CPAN
        - bash -o errexit buildme.sh
    - name: "osx:10.12_xcode:8.0"
      language: cpp
      os: osx
      osx_image: xcode8
      addons: {homebrew: {update: [true]}}
      addons: {homebrew: {packages: [[nasm], [rsync]]}}
      env:
        - EVERYTHING=awesome
      script:
        - cd CPAN
        - bash -o errexit buildme.sh
    - name: "osx:10.11_xcode:7.3"
      language: cpp
      os: osx
      osx_image: xcode7.3
      addons: {homebrew: {update: [true]}}
      addons: {homebrew: {packages: [[nasm], [rsync]]}}
      env:
        - EVERYTHING=awesome
      script:
        - cd CPAN
        - bash -o errexit buildme.sh

install: true

script:
  - cd CPAN
  - bash -o errexit buildme.sh

