matrix:
  include:
    - name: "alac"
      language: c
      os:
        - linux
        - osx
      compiler:
        - gcc
      script:
        - cd alac_decoder
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make -f Makefile.osx        ; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make      ; fi

notifications:
  email:
    - m.kempe@gmail.com

