language: perl
perl:
  - "5.18"
os:
  - linux

env:
  - CC=clang && CXX=clang++

cache: ccache

addons:
  apt:
    packages:
      - nasm
      - rsync
      - zlib1g-dev
      - libmodule-install-perl

matrix:
  include:
    - name: "perl_osx"
      language: cpp
      os: osx
      script:
        - perl -V

install: true

script:
  - cd CPAN
  - bash -o errexit buildme.sh

notifications:
  email:
    - m.kempe@gmail.com

